### ISSUE TITLE
fj.data.LazyString.toString cause infinite recursion on Android

### ISSUE THREAD

**Issue by alexd6631** [functionaljava/functionaljava#114]
Context : Android (tested on 5.0.1) with FJ 4.2

Trying to print an Option with : 
`System.out.println(Option.some(45));`

cause an infinite recursion in LazyString.toString : 
```
ERR: stack=java.lang.StackOverflowError: stack size 8MB
            at java.lang.StringBuilder.<init>(StringBuilder.java:81)
            at fj.data.LazyString.toString(LazyString.java:111)
...
```

it seems the StringBuilder constructor call .toString on CharSequence instead of iterating on the characters, leading to a recursion loop.

**Comment by alexd6631** [comment]
Just stumbled accross the commit : https://github.com/functionaljava/functionaljava/commit/c66943afc92e2a7fa642ec4358df38c3e120d7b1

It should fix the issue.
